version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: help/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

build:
  apt_packages:
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-italian