version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-italian

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: help/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
