CREATE TABLE 'tavole' ( "ogc_fid" INTEGER PRIMARY KEY AUTOINCREMENT, 'nome' VARCHAR(255), 'numero' INTEGER, "GEOMETRY" POLYGON);;

CREATE TABLE 'nome_sezione' ( "ogc_fid" INTEGER PRIMARY KEY AUTOINCREMENT, 'nome' VARCHAR(50), "GEOMETRY" POINT);;

