services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      # DISK_SIZE: "256G"  # default 64GB
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "qgis"
      PASSWORD: "qgis"
      LANGUAGE: "Italian"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./win11:/storage
      # - ./Win11_25H2_Italian_x64.iso:/boot.iso  # skip download and use custom ISO
      -  ./oem:/oem  # OEM folder for unattended installation
      - ~/:/shared  # share home folder
    restart: unless-stopped
    stop_grace_period: 2m
